{"humvee" "HMMWV"} 
{"humvee_m134" "M1025 Humvee"}
{"humvee_mk19" "Humvee Mk.19"}
{"humvee_m134" "Humvee M134"}
{"humvee_tow2" "Humvee TOW 2"}
{"browning_trenoga" "Browning Trenoga"}
{"t62" "Т-62"}
{"m1_abrams" "M1 Abrams"}
{"m1a1_abrams" "M1 Abrams"}
{"m1a1ha_abrams" "M1 Abrams"}
{"m1a2_abrams" "M1 Abrams"}
{"m1ip_abrams" "M1 Abrams"}
{"m106a2" "M106A2"}
{"m113" "M106A2"}
{"m113" "M113"}
{"m113_acav" "M113"}
{"m150" "M150"}
{"m577" "M577"}
{"m901_itv" "M901"}
{"m109a2" "M901"}
{"m109a2" "M109A7 Paladin"}
{"m109a6_paladin" "M109A7 Paladin"}
{"m110" "M110"}
{"m110" "M163 CS"}