{"belt_a" "Бронежилет"}
{"belt_a_rpg" "belt_a_rpg"}
{"belt_a_sniper" "belt_a_sniper"}
{"eng_razgruz_medic" "Британский бронежилет санитара"}
{"eng_razgruz1" "Бронижелет ВС Британии"}
{"eng_razgruz2" "Бронижелет ВС Британии"}
{"eng_razgruz3" "Бронижелет ВС Британии"}
{"vest_6b5" "Бронижелет 6Б5"}
{"vest_6b5_2" "Бронижелет 6Б5"}
{"vest_comm" "vest_comm"}
{"vest_comm_sov" "vest_comm_sov"}
{"bdu_cap" "bdu_cap"}
{"bdu_cap_ranger" "bdu_cap_ranger"}
{"beret_brit_army" "Британский берет"}
{"beret_brit_ghurka" "Британский берет спецназа"}
{"beret_brit_sas" "Берет SAS"}
{"beret_brit_tank" "Британский берет танкиста"}
{"beret_brit_tank2" "Британский берет танкиста"}
{"beret_brit_vdv" "Британский берет ВДВ"}
{"beret_brit_vdv" "Британский берет ВДВ"}
{"boonie_hat_bdu" "Панама"}
{"cap_rus_paratrooper" "Фуражка"}
{"cap_rus_pilot" "Шлемофон пилота"}
{"cap_rus_regular" "Пилотка"}
{"cap_rus_sniper" "Снайперская пилотка"}
{"cap_rus_sql" "Фуражка ПВ"}
{"cap_rus_tankman" "Такновый шлемофон"}
{"cap_rus_tankman" "Такновый шлемофон"}
{"hat_brit" "hat_brit"}
{"helm_brit_army" "Каска ВС Британии"}
{"helm_brit_camo" "Каска ВС Британии"}
{"helm_brit_vdv" "Каска ВДВ Британии"}
{"helm_brit_vdv" "Каска ВДВ Британии"}
{"helmet_rus_guard" "Каска СА"}
{"kepi_brit" "kepi_brit"}
{"kepi_brit" "kepi_brit"}
{"pasgt_helmet" "pasgt_helmet_cpt"}
{"pasgt_helmet_glasses" "pasgt_helmet_glasses"}
{"l109_grenade" "l109"}
{"m61_grenade" "M61"}
{"m67_grenade" "M67"}
{"rgd" "РГД"}
{"rgo" "РГО"}
{"rgn" "РГН"}
