{"gunstav" "Carl Gustaf"} 
{"l1a1_rpg" "l1a1"} 
{"law80" "Law 80"} 
{"m47_dragon" "Dragon"}
{"m72law" "M72 LAW"}
{"m79" "M79"}
{"m202" "M202"}
{"rpg7" "РПГ-7"}
{"rpg18" " РПГ-18 «Муха»"}
{"rpg27" " РПГ-27 «Таволга»"}
{"rpg29" "РПГ-29 «Вампир»"}
{"rpg75" "РПГ-75"}
{"smaw" "Smaw"}
{"browningm1917a1" "Browning M1917"}
{"dshk" "ДШК"}
{"dshk_aa" "ДШК"}
{"dshk_t" "ДШК"}
{"dshkm" "ДШК"}
{"l4a4bren" "Bren L4A4"}
{"l86" "L86 LSW"}
{"l4a4bren" "Bren L4A4"}
{"m60" "М60"}
{"m134_minigun" "M134 Minigun"}
{"m249" "M249 SAW"}
{"minimi " "FN Minimi"}
{"minimi_jp" "FN Minimi"}
{"minimi_s" "FN Minimi"}
{"pkm" "ПКМ"}
{"pkt " "ПКТ"}
{"rpk74" "РПК-74"}
{"sgmt" "СГМТ"}
{"sgmtx2" "СГМТ"}
{"aps" "АПС"}
{"beretta92" "Beretta 92"}
{"coltm1911a1" "Colt M1911A1"}
{"glock17" "Glock 17"}
{"l9pis" "Browning Hi-Power"}
{"pb" "ПБ"}
{"pm_sil" "ПМ"}
{"pss" "ПСС"}
{"aug" "Steyr AUG"}
{"car15" "Car-15"}
{"car15_s" "AR-15"}
{"l22_carbine" ""}
{"l85" "L-85"}
{"l85_s" "L-85"}
{"m4a1" "M4"}
{"m16_20" "M16"}
{"m16a1" "M16"}
{"m16a1_dmr" "M16"}
{"m16a1_s" "M16"}
{"m16a2" "M16"}
{"m16a2" "M16"}
{"mk16" "M16"}
{"remington 870" "Remington 870"}
{"val" "АС «Вал»"}
{"vintorez" "ВСС «Винторез»"}
{"l96a1" "L96A1"}
{"m21" "M21"}
{"m24_sni" "M24"}
{"m40a1" "M24"}
{"m24_sni" "M40"}
{"m24_sni" "M82A1"}
{"svd" "СВД"}
{"ak47" "АК-47"}
{"ak74" "АК-74"}
{"ak74b" "АК-74Б"}
{"akm" "АКМ"}
{"akms" "АКМС"} 
{"aks74u" "АКС-74У"}
{"aks74u_3" "АКС-74У"}
{"aks74u_4" "АКС-74У"}
{"40mm_mk19" "Mk 19 40-мм"}
{"tow" "TOW"}
{"115mm_2a20" "2А20 115 ММ"}
{"sterling" "Sterling"}
{"20mm_m61a1" "20 мм M61 Vulcan"}
{"105mm_m68a1" "105 мм M68"}
{"120mm_m256" "120-мм M256"}
{"120mm_m256a2" "120-мм M256"}
{"155mm_m185" "155 M109"}
{"155mm_m284" "155 M284"}
{"203mm_m201a" "203 мм М110"}
